export const invetments = [
  {
    nome: "CDB Banco Master",
    prazo: "08/01/2026",
    valor_aplicado: "R$ 182,15",
    valor: "R$ 214,12",
    data_aquisicao: "-",
    tipo: "CDB",
    tipo_taxa: "Pre fixado",
    taxa: "13,72",
    atrelado: "a.a",
    instituicao: "Nubank",
  },
  {
    nome: "CDB Banco Master",
    prazo: "06/05/2026",
    valor_aplicado: "R$ 417,00",
    valor: "R$ 493,57",
    data_aquisicao: "",
    tipo: "CDB",
    tipo_taxa: "Pos fixado",
    taxa: "120%",
    atrelado: "cdi",
    instituicao: "Nubank",
  },
  {
    nome: "CDB Banco Master",
    prazo: "22/02/2027",
    valor_aplicado: "R$ 1.261,50",
    valor: "R$ 1.431,46",
    data_aquisicao: "",
    tipo: "CDB",
    tipo_taxa: "Pre fixado",
    taxa: "12,72",
    atrelado: "a.a",
    instituicao: "Nubank",
  },
  {
    nome: "CDB Banco Master",
    prazo: "24/02/2027",
    valor_aplicado: "R$ 1.282,12",
    valor: "R$ 1.454,85",
    data_aquisicao: "",
    tipo: "CDB",
    tipo_taxa: "Pre fixado",
    taxa: "12,72",
    atrelado: "a.a",
    instituicao: "Nubank",
  },
  {
    nome: "CDB Banco Master",
    prazo: "21/05/2027",
    valor_aplicado: "R$ 1.469,53",
    valor: "R$ 1.668,91",
    data_aquisicao: "",
    tipo: "CDB",
    tipo_taxa: "Pre fixado",
    taxa: "12,81",
    atrelado: "a.a",
    instituicao: "Nubank",
  },
  {
    nome: "CDB Meu Porquinho",
    prazo: "-",
    valor_aplicado: "-",
    valor: "R$ 137,69",
    data_aquisicao: "",
    tipo: "CDB",
    tipo_taxa: "Pos fixado",
    taxa: "100%",
    atrelado: "cdi",
    instituicao: "Inter",
  },
  {
    nome: "CDB LIQUIDEZ DIÁRIA",
    prazo: "-",
    valor_aplicado: "-",
    valor: "R$ 20.555,71",
    data_aquisicao: "21/05/2024",
    tipo: "CDB",
    tipo_taxa: "Pos fixado",
    taxa: "100%",
    atrelado: "cdi",
    instituicao: "Inter",
  },
  {
    nome: "CDB 720 Dias",
    prazo: "02/06/2026",
    valor_aplicado: "R$ 2.029,06",
    valor: "R$ 2.045,02",
    data_aquisicao: "",
    tipo: "CDB",
    tipo_taxa: "",
    taxa: "",
    atrelado: "",
    instituicao: "Inter",
  },
  {
    nome: "CDB C6 PREFIXADO 3 ANOS",
    prazo: "17/09/2026",
    valor_aplicado: 1020.0,
    valor: 1101.96,
    data_aquisicao: "18/09/2023",
    tipo: "CDB",
    tipo_taxa: "Pre fixado",
    taxa: "12,45",
    atrelado: "a.a",
    instituicao: "C6",
  },
];
